### ISSUE TITLE
New Release for Django 1.11 Support

### ISSUE THREAD

**Issue by richardowen** [alexhayes/django-pdfkit#7]
I can see some support for Django 1.11 was added in 81b871a. Could a new release be published to PyPI so that this can be used easily? Thanks!

**Comment by f213** [comment]
@alexhayes any news? Hay can i help for new release to happen?

**Comment by alexhayes** [comment]
Hey folks, sorry for the delay I'll try sort this out tomorrow.

On 4 Aug 2017 9:16 PM, "Fedor Borshev" <notifications@github.com> wrote:

@alexhayes <https://github.com/alexhayes> any news? Hay can i help for new
release to happen?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexhayes/django-pdfkit/issues/7#issuecomment-320223975>,
or mute the thread
